[package]
name = "fnum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.33.3"
structopt = {version="0.3.22", features=["paw"]}
paw="1.0.0"